development:
  adapter: postgresql
  encoding: unicode
  database: js_toolkit_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: js_toolkit_test
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
